# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "/home/deanmarchiori/workspace/r-model-template/inst/deploy")
v <- vetiver_pin_read(b, "sydney-beach-gam")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
